KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_SCHEMA_REGISTRY: none
SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: igroup
SERVICE_USER_PASSWORD: itest
SAF_BASE_URL: none
STS_APIKEY: none
JOURNALPOST_APIKEY: none
AZURE_APP_WELL_KNOWN_URL: none
AZURE_APP_CLIENT_ID: none
AZURE_APP_CLIENT_SECRET: none
KLAGE_DITTNAV_API_CLIENT_ID: e849947a-8ba3-488c-bc02-2f39d09c0111