KAFKA_BOOTSTRAP_SERVERS: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
KAFKA_SCHEMA_REGISTRY: https://kafka-schema-registry.nais-q.adeo.no
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw-q1.oera.no/security-token-service
SERVICE_USER_USERNAME: srvklage-dittnav
SAF_BASE_URL: https://api-gw-q1.oera.no/saf-api/graphql
KAFKA_TOPIC: aapen-dok-journalfoering-v1-q1