KAFKA_BOOTSTRAP_SERVERS: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
KAFKA_SCHEMA_REGISTRY: https://kafka-schema-registry.nais-q.adeo.no
SECURITY_TOKEN_SERVICE_REST_URL: https://security-token-service.nais.preprod.local
SERVICE_USER_USERNAME: srvklage-dittnav
SAF_BASE_URL: https://saf-q1.nais.preprod.local/graphql
KAFKA_TOPIC: aapen-dok-journalfoering-v1-q1
VARSEL_URI: mq://b27apvl176.preprod.local:1413/MQ1LSC02
VARSEL_CHANNEL_NAME: Q1_KLAGE_VARSEL
VARSEL_QUEUE_NAME: QA.Q1_VARSELPRODUKSJON.SEND_VARSEL
VARSEL_USERNAME: srvappserver
KLAGE_DITTNAV_API_CLIENT_ID: 9ba0e760-d28c-44d2-8cae-8a1dc9b4584f
KLAGE-DITTNAV-API_SERVICE_URL: https://klage-dittnav-api.dev.nav.no