KAFKA_BOOTSTRAP_SERVERS: localhost:9092
SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: igroup
SERVICE_USER_PASSWORD: itest
JOARK_SERVICE_URL: http://localhost:1234
STS_APIKEY: none
JOURNALPOST_APIKEY: none
VARSEL_USERNAME: username
VARSEL_URI: mq://b27apvl176.preprod.local:1413/MQ1LSC02
VARSEL_CHANNEL_NAME: Q1_KLAGE_VARSEL
VARSEL_QUEUE_NAME: QA.Q1_VARSELPRODUKSJON.SEND_VARSEL
