KAFKA_BOOTSTRAP_SERVERS: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
KAFKA_SCHEMA_REGISTRY: https://kafka-schema-registry.tpa:8081
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw.oera.no/security-token-service
SERVICE_USER_USERNAME: srvklage-dittnav
SAF_BASE_URL: https://api-gw.oera.no/saf-api/graphql
KAFKA_TOPIC: aapen-dok-journalfoering-v1-p
