spring:
  main:
    banner-mode: OFF
  codec:
    max-in-memory-size: 2MB
  sleuth:
    propagation-keys:
      - Nav-Callid
      - Nav-Consumer-Id
    log:
      slf4j:
        whitelisted-mdc-keys:
          - Nav-Callid
          - Nav-Consumer-Id

server:
  port: 7076
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

KAFKA_GROUP_ID: klage-joark-listener
KAFKA_TOPIC: aapen-dok-journalfoering-v1

navCallId: Nav-Callid
navConsumerId: Nav-Consumer-Id
xNavApiKey: x-nav-apiKey

KLAGE-DITTNAV-API_SERVICE_URL: http://klage-dittnav-api
KLAGE_DITTNAV_API_APP_NAME: klage-dittnav-api

