//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.13 at 06:43:56 PM CEST
//


package no.nav.melding.virksomhet.varsel.v1.varsel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AktoerId complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AktoerId">
 *   &lt;complexContent>
 *     &lt;extension base="{http://nav.no/melding/virksomhet/varsel/v1/varsel}Aktoer">
 *       &lt;sequence>
 *         &lt;element name="aktoerId" type="{http://nav.no/melding/virksomhet/varsel/v1/varsel}Identifikator"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AktoerId", propOrder = {
    "aktoerId"
})
public class AktoerId
    extends Aktoer
{

    @XmlElement(required = true)
    protected String aktoerId;

    /**
     * Gets the value of the aktoerId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAktoerId() {
        return aktoerId;
    }

    /**
     * Sets the value of the aktoerId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAktoerId(String value) {
        this.aktoerId = value;
    }

}
