//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.13 at 06:43:56 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nav.no/melding/virksomhet/varsel/v1/varsel")
package no.nav.melding.virksomhet.varsel.v1.varsel;
