//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.13 at 06:43:56 PM CEST
//


package no.nav.melding.virksomhet.varsel.v1.varsel;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Varsel complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Varsel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mottaker" type="{http://nav.no/melding/virksomhet/varsel/v1/varsel}Aktoer"/>
 *         &lt;element name="varslingstype" type="{http://nav.no/melding/virksomhet/varsel/v1/varsel}Varslingstyper"/>
 *         &lt;element name="parameterListe" type="{http://nav.no/melding/virksomhet/varsel/v1/varsel}Parameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="utloepstidspunkt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Varsel", propOrder = {
    "mottaker",
    "varslingstype",
    "parameterListe",
    "utloepstidspunkt"
})
public class Varsel {

    @XmlElement(required = true)
    protected Aktoer mottaker;
    @XmlElement(required = true)
    protected Varslingstyper varslingstype;
    protected List<Parameter> parameterListe;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar utloepstidspunkt;

    /**
     * Gets the value of the mottaker property.
     *
     * @return
     *     possible object is
     *     {@link Aktoer }
     *
     */
    public Aktoer getMottaker() {
        return mottaker;
    }

    /**
     * Sets the value of the mottaker property.
     *
     * @param value
     *     allowed object is
     *     {@link Aktoer }
     *
     */
    public void setMottaker(Aktoer value) {
        this.mottaker = value;
    }

    /**
     * Gets the value of the varslingstype property.
     *
     * @return
     *     possible object is
     *     {@link Varslingstyper }
     *
     */
    public Varslingstyper getVarslingstype() {
        return varslingstype;
    }

    /**
     * Sets the value of the varslingstype property.
     *
     * @param value
     *     allowed object is
     *     {@link Varslingstyper }
     *
     */
    public void setVarslingstype(Varslingstyper value) {
        this.varslingstype = value;
    }

    /**
     * Gets the value of the parameterListe property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterListe property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterListe().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     *
     *
     */
    public List<Parameter> getParameterListe() {
        if (parameterListe == null) {
            parameterListe = new ArrayList<Parameter>();
        }
        return this.parameterListe;
    }

    /**
     * Gets the value of the utloepstidspunkt property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getUtloepstidspunkt() {
        return utloepstidspunkt;
    }

    /**
     * Sets the value of the utloepstidspunkt property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setUtloepstidspunkt(XMLGregorianCalendar value) {
        this.utloepstidspunkt = value;
    }

}
